service: pdf-a11y-check 
 
provider:
 name: aws
 runtime: python3.9
 region: eu-central-1
 memorySize: 256

plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
 wsgi:
   app: app.app
   packRequirements: false
 pythonRequirements:
   dockerizePip: true 	
functions:
 app:
   handler: wsgi_handler.handler
   events:
     - http: POST /
